# Generated by Django 4.2.2 on 2023-06-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_food_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food',
            new_name='food_consumed',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='proteins',
            new_name='protein',
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.ImageField(upload_to=''),
        ),
    ]
