# Generated by Django 4.1.6 on 2023-09-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_food_consume_food_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(),
        ),
    ]
